__default__:
    queue: wgs.q
    threads: 20
    excl: excl=1
    name: "WGSsomatic_{rule}_{wildcards.sname}"
    output: "WGSsomatic_{rule}_{wildcards.sname}.stdout"
    error: "WGSsomatic_{rule}_{wildcards.sname}.stderr"

mapping:
    name: "WGSsomatic_{rule}_{wildcards.fastqpattern}"
    output: "WGSsomatic_{rule}_{wildcards.fastqpattern}.stdout"
    error: "WGSsomatic_{rule}_{wildcards.fastqpattern}.stderr"
    threads: 40

rtgtools_eval:
    threads: 10

dedup:
    threads: 20

realign_mapping:
    threads: 20

baserecal:
    threads: 20

tnscope:
    threads: 40

tnscope_modelfilter:
    threads: 20

tnscope_vcffilter:
    threads: 2

dnascope:
    threads: 40

generate_tdf:
    threads: 4

dnascope_modelfilter:
    threads: 20

dnascope_vcffilter:
    threads: 2

ballele_plot:
    threads: 2

wgs_coverage:
    threads: 4

y_coverage:
    threads: 4

share_to_igv:
    threads: 2

manta_somatic:
    threads: 20

manta_germline:
    threads: 20

manta_summary:
    threads: 4

alissa_vcf:
    threads: 1

pindel:
    threads: 4

cutadapt:
    threads:  1
    excl: excl=1

insilico_coverage:
    threads: 2
    excl: excl=1
