---
novaseq_687_gc:
  root_path: "/seqstore/instruments/novaseq_687_gc/"
  demultiplex_path: "/seqstore/instruments/novaseq_687_gc/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A00687_[0-9]{4}_.{10}$'

novaseq_A01736:
  root_path: "/seqstore/instruments/novaseq_A01736/"
  demultiplex_path: "/seqstore/instruments/novaseq_A01736/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A01736_[0-9]{4}_.{10}$'

previous_runs_file_path: 'novaseq_runlist.txt'

igv:
  GMS-BT: 'barncancer_hg38'
  GMS-AL: 'barncancer_hg38'
  G21-004: 'susanne.fransson'

hg38ref:
  GMS-BT: 'yes'
  GMS-AL: 'yes'

workingdir: '/medstore/results/wgs/wgs_somatic'
